version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - housemmimoun27
    assignees:
      - housemmimoun27
    open-pull-requests-limit: 5
